#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

# ./makeMesh


# runApplication setFields
\cp -r 0.org 0
runApplication decomposePar
runParallel $application 2
runApplication reconstructPar
# runApplication $application

# ----------------------------------------------------------------- end-of-file
